## Data Wrangling

> Joseph Cornell

## Package Import

In [1]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
%config InlineBackend.figure_format = 'retina'

## Data Import

### Import

In [3]:
# import the "ICU_Mortality.csv" dataset as a panda dataframe and assign it to a variable called "df"
df = pd.read_csv("ICU_Mortality.csv")

In [4]:
# import "https://raw.githubusercontent.com/juanklopper/TutorialData/refs/heads/main/ICU_Mortality.csv" as a panda dataframe and assign it to a variable called "df"
# df = pd.read_csv("https://raw.githubusercontent.com/juanklopper/TutorialData/refs/heads/main/ICU_Mortality.csv")

### Data Verification

In [5]:
type(df)

pandas.DataFrame

In [7]:
# Return the first five rows of the dataframe
df.head(10)

  Mortality  Age   WCC    HB Diabetes           Class
0      Died   69  12.0  11.7      NaN  Non-infectious
1      Died   73   9.0  13.2      NaN  Non-infectious
2      Died   53  16.4  11.1      NaN  Non-infectious
3      Died   74  10.1  11.2  Type II      Infectious
4      Died   69  10.2  15.0   Type I      Infectious
5      Died   54  11.3  14.8  Type II  Non-infectious
6      Died   71  11.0  13.0   Type I      Infectious
7      Died   47   7.8   7.2      NaN      Infectious
8      Died   56  19.0   9.4   Type I  Non-infectious
9      Died   45  16.3  13.7  Type II  Non-infectious

In [8]:
# return the last five rows of the dataframe 'df'
df.tail()

    Mortality  Age   WCC    HB Diabetes           Class
306      Died   75   8.4  11.0   Type I  Non-infectious
307  Survived   56  14.0   9.0      NaN      Infectious
308  Survived   45  15.0   9.9      NaN      Infectious
309  Survived   45  15.2   7.0      NaN      Infectious
310  Survived   54  16.0  10.0      NaN      Infectious

In [9]:
# Return the shape of the dataframe 'df'
df.shape

(311, 6)

In [10]:
df.columns

Index(['Mortality', 'Age', 'WCC', 'HB', 'Diabetes', 'Class'], dtype='str')

Data dictionary

| Variable | Description |
|:---|:---|
| Mortality | $\text{Died}$ indicates the participant died <br> $\texttt{Survived}$ that participant died |
| Age | Integer age of participant |

In [12]:
# Return information about 'df'
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Mortality  311 non-null    str
 1   Age        311 non-null    int64
 2   WCC        311 non-null    float64
 3   HB         311 non-null    float64
 4   Diabetes   213 non-null    str
 5   Class      311 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 14.7 KB

## Filtering and Selection

In [16]:
# Return the "Mortality" column
df["Mortality"]

0          Died
1          Died
2          Died
3          Died
4          Died
         ...
306        Died
307    Survived
308    Survived
309    Survived
310    Survived
Name: Mortality, Length: 311, dtype: str

In [18]:
# Return the "Age" column and assign it to the variable "Age"
age = df.Age

In [19]:
age

0      69
1      73
2      53
3      74
4      69
       ..
306    75
307    56
308    45
309    45
310    54
Name: Age, Length: 311, dtype: int64

In [23]:
type(age)

pandas.Series

In [24]:
# Return the "age" column as Numpy array and assign it to the variable 'age_array'
age_array = df.Age.to_numpy()
age_array

array([69, 73, 53, 74, 69, 54, 71, 47, 56, 45, 69, 51, 74, 66, 57, 68, 53,
       45, 74, 45, 74, 60, 49, 45, 51, 63, 61, 54, 74, 48, 68, 75, 72, 49,
       51, 64, 61, 61, 49, 75, 69, 60, 65, 55, 63, 72, 62, 59, 73, 59, 45,
       67, 53, 55, 60, 61, 69, 71, 45, 74, 51, 68, 48, 49, 65, 48, 61, 73,
       64, 73, 74, 75, 52, 52, 66, 70, 57, 55, 69, 46, 50, 50, 61, 63, 62,
       52, 69, 54, 47, 53, 64, 75, 58, 59, 69, 58, 49, 57, 57, 56, 48, 49,
       47, 59, 60, 43, 62, 53, 59, 51, 55, 49, 49, 50, 51, 44, 46, 51, 48,
       51, 80, 63, 61, 44, 41, 73, 57, 45, 50, 53, 53, 50, 56, 58, 58, 67,
       56, 60, 73, 45, 61, 61, 54, 47, 49, 35, 84, 64, 52, 69, 63, 49, 40,
       36, 40, 72, 57, 69, 47, 50, 49, 47, 64, 48, 53, 52, 80, 51, 57, 73,
       57, 56, 57, 76, 54, 53, 45, 51, 62, 56, 55, 53, 63, 37, 58, 65, 58,
       53, 53, 61, 44, 42, 51, 48, 40, 31, 59, 59, 42, 55, 36, 41, 42, 53,
       53, 58, 37, 58, 52, 39, 62, 73, 56, 54, 66, 53, 58, 41, 66, 60, 39,
       35, 74, 71, 66, 57, 34, 85, 44, 42, 40, 54, 44, 75, 41, 40, 48, 56,
       46, 47, 57, 63, 42, 47, 67, 34, 43, 53, 61, 53, 53, 63, 66, 73, 36,
       58, 23, 66, 56, 53, 44, 67, 50, 50, 49, 49, 51, 57, 60, 56, 47, 48,
       73, 69, 62, 59, 54, 66, 68, 55, 45, 59, 56, 54, 70, 59, 47, 51, 36,
       60, 67, 51, 53, 73, 40, 38, 82, 65, 34, 59, 66, 56, 67, 76, 77, 77,
       75, 56, 45, 45, 54])

In [25]:
type(age_array)

numpy.ndarray

In [26]:
age_array.mean()

np.float64(56.456591639871384)

In [27]:
df.iloc[0]

Mortality              Died
Age                      69
WCC                    12.0
HB                     11.7
Diabetes                NaN
Class        Non-infectious
Name: 0, dtype: object

In [52]:
df.iloc[[0,2,7]]

  Mortality  Age   WCC    HB Diabetes           Class
0      Died   69  12.0  11.7      NaN  Non-infectious
2      Died   53  16.4  11.1      NaN  Non-infectious
7      Died   47   7.8   7.2      NaN      Infectious

In [32]:
df.iloc[-3:]

    Mortality  Age   WCC    HB Diabetes       Class
308  Survived   45  15.0   9.9      NaN  Infectious
309  Survived   45  15.2   7.0      NaN  Infectious
310  Survived   54  16.0  10.0      NaN  Infectious

In [33]:
df.iloc[0:5, 0:3]

  Mortality  Age   WCC
0      Died   69  12.0
1      Died   73   9.0
2      Died   53  16.4
3      Died   74  10.1
4      Died   69  10.2

In [37]:
df.loc[:, ["Age", "Mortality"]]

     Age Mortality
0     69      Died
1     73      Died
2     53      Died
3     74      Died
4     69      Died
..   ...       ...
306   75      Died
307   56  Survived
308   45  Survived
309   45  Survived
310   54  Survived

[311 rows x 2 columns]

In [38]:
# Return the unique values in the "Mortality" column
df.Mortality.unique()

<StringArray>
['Died', 'Survived']
Length: 2, dtype: str

In [42]:
# select only rows with age less than 50 and assign it to the variable "df_young"
df_young = df[df.Age < 50]

In [43]:
df_young.Mortality

7          Died
9          Died
17         Died
19         Died
22         Died
         ...
294    Survived
295    Survived
298    Survived
308    Survived
309    Survived
Name: Mortality, Length: 86, dtype: str

In [45]:
df.loc[df.Age < 50, "Mortality"]

7          Died
9          Died
17         Died
19         Died
22         Died
         ...
294    Survived
295    Survived
298    Survived
308    Survived
309    Survived
Name: Mortality, Length: 86, dtype: str

In [ ]:
df.loc[df.Mortality == "Died", "Age",]

0      69
1      73
2      53
3      74
4      69
       ..
302    67
303    76
304    77
305    77
306    75
Name: Age, Length: 104, dtype: int64

In [51]:
# Return the "Age" column for rows where the "Mortality" column is equal to "Died", "Age" less than "50", and "Class" equal to "Infectious"
df.loc[(df.Mortality == "Died") & (df.Age < 50) & (df.Class == "Infectious"), "Age"]

7      47
19     45
23     45
33     49
50     45
58     45
88     47
101    49
Name: Age, dtype: int64